MASCore/MASCore/Controllers/SolicitudDeInformacionController.cs
using ClosedXML.Excel;
using MASCore.Exportar;
using MASCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Xceed.Words.NET;
using DevExtreme.AspNet.Mvc;
using Newtonsoft.Json;
using DevExtreme.AspNet.Data;
using Newtonsoft.Json.Linq;
using MASCore.DataModel;
using Microsoft.AspNetCore.Hosting;


namespace MASCore.Controllers
{
    public class SolicitudDeInformacionController : BaseController
    {
        //private BDMasContextEnt db = new BDMasContextEnt();
        FuncionesProcedimientos FunProc = new FuncionesProcedimientos();

        //
        // GET: /SolicitudDeInformacion/
        public ActionResult Index()
        {
            TMasSolInfoCedulas TMSol = new TMasSolInfoCedulas();
            return View(TMSol);
        }

        public ActionResult BuscaSolInfo() // carga la pantalla para buscar
        {
            SolicitudDeInformacionEntradaDatosBusqueda ModeloTmp = new SolicitudDeInformacionEntradaDatosBusqueda();
            ModeloTmp.FechaInicial = DateTime.Now;
            ModeloTmp.FechaFinal = DateTime.Now;

            //ViewBag.ofp = FunProc.LlenarResultadoGenerico("responsableofp");
            //ViewBag.asunto = FunProc.LlenarResultadoGenerico("asunto");
            //ViewBag.medio = FunProc.LlenarResultadoGenerico("medio");
            //ViewBag.estado = FunProc.LlenarResultadoGenerico("estadosolinfo");
            //ViewBag.ciudad = FunProc.BuscaResultadoGenericoConParametrosLista("CIUDAdsolinfo", "", "");
            //ViewBag.Dependencias = FunProc.LlenarResultadoGenerico("dependencia");
            
            List<BuscaSolicitudesDeInformacion_Result> ResultadoListaSolInfoSP = new List<BuscaSolicitudesDeInformacion_Result>();
            ModeloTmp.ResultadoListaSolInfoSP = ResultadoListaSolInfoSP;
            //Session.Remove("SessionResultadoListaSolInfoSPTmp");
            //Session["SessionResultadoListaSolInfoSPTmp"] = ModeloTmp.ResultadoListaSolInfoSP;
            return View(ModeloTmp);
        }

        [HttpPost]
        public ActionResult BuscaSolInfo(SolicitudDeInformacionEntradaDatosBusqueda ModeloTmp) //Accion del botón par buscar
        {
            //ViewBag.ofp = FunProc.LlenarResultadoGenerico("responsableofp");
            //ViewBag.asunto = FunProc.LlenarResultadoGenerico("asunto");
            //ViewBag.medio = FunProc.LlenarResultadoGenerico("medio");
            //ViewBag.estado = FunProc.LlenarResultadoGenerico("estadosolinfo");
            //ViewBag.ciudad = FunProc.BuscaResultadoGenericoConParametrosLista("CIUDAdsolinfo", "", "");
            //ViewBag.Dependencias = FunProc.LlenarResultadoGenerico("dependencia");
            List<BuscaSolicitudesDeInformacion_Result> ResultadoListaSolInfoSPTmp = new List<BuscaSolicitudesDeInformacion_Result>();
            ModeloTmp.ResultadoListaSolInfoSP = ResultadoListaSolInfoSPTmp;
            //Session["SessionResultadoListaSolInfoSPTmp"] = ModeloTmp.ResultadoListaSolInfoSP;
            if (ModelState.IsValid)
            {
                #region "VALIDACIONES"
                Boolean Valido = true;
                if (ModeloTmp.FechaInicial > ModeloTmp.FechaFinal)
                {
                    ViewBag.NoValidoPor = "No es posible realizar la búsqueda, la fecha inicial no puede ser mayor a la fecha final. Verificar.";
                    Valido = false;
                }
                #endregion
                if (Valido == true)
                {
                    //Aquí separamos el valor de Embarcación, quitamos la matricula y el RNP.

                    //Session["embarcacion"] = "";

                    if (ModeloTmp.Embarcacion != null)
                    {
                        string barco = ModeloTmp.Embarcacion.Replace(" | ", "|");
                        String[] arrayString = barco.Split('|');
                        //MODIFICADO POR SZ EL 09/01/2017
                        String nombreBarco = arrayString[0];
                        String matriculaBarco = arrayString[1];
                        String RNPBarco = arrayString[2];

                        //MODIFICADO EN VEZ DE TRAER EL NOMBRE DEL BARCO TRAEMOS EL RNP
                        //Session["embarcacion"] = RNPBarco;
                    }
                    //VER VALIDACIÓN DE BARCO PARA CUANDO SEA NULO NO TRUENE.

                    ModeloTmp.ResultadoListaSolInfoSP = ModeloTmp.EncuentraLasSolInfoSP(ModeloTmp.FechaInicial, ModeloTmp.FechaFinal,
                        ModeloTmp.medio, ModeloTmp.asunto, ModeloTmp.dependencia, ModeloTmp.OFP, ModeloTmp.solicitante, ModeloTmp.folio, "",// HttpContext.Session["embarcacion"],
                        ModeloTmp.Estado, ModeloTmp.Ciudad);
                }

                //Session["SessionResultadoListaSolInfoSPTmp"] = ModeloTmp.ResultadoListaSolInfoSP;

                //No se usa SessionResultadoListaSolInfo
                List<BuscaSolicitudesDeInformacion_Result> ResultadoListaSolInfo = ModeloTmp.ResultadoListaSolInfoSP;
                //Session["SessionResultadoListaSolInfo"] = ResultadoListaSolInfo;
            }

            string ParametrosDeBusqueda = "";

            ParametrosDeBusqueda += "Desde " + ModeloTmp.FechaInicial.ToShortDateString() + " Hasta " + ModeloTmp.FechaFinal.ToShortDateString() + " |";

            if (ModeloTmp.solicitante != null && ModeloTmp.solicitante.Length > 0)
                ParametrosDeBusqueda += " Solicitante: " + ModeloTmp.solicitante + " |";
            if (ModeloTmp.folio != null && ModeloTmp.folio.Length > 0)
                ParametrosDeBusqueda += " Folio: " + ModeloTmp.folio + " |";
            if (ModeloTmp.asunto != null && ModeloTmp.asunto.Length > 0)
                ParametrosDeBusqueda += " Asunto: " + ModeloTmp.asunto + " |";
            if (ModeloTmp.OFP != null && ModeloTmp.OFP.Length > 0)
                ParametrosDeBusqueda += " OFP: " + ModeloTmp.OFP + " |";
            if (ModeloTmp.medio != null && ModeloTmp.medio.Length > 0)
                ParametrosDeBusqueda += " Medio: " + ModeloTmp.medio + " |";
            if (ModeloTmp.dependencia != null && ModeloTmp.dependencia.Length > 0)
                ParametrosDeBusqueda += " Dependencia: " + ModeloTmp.dependencia + " |";

            if (ParametrosDeBusqueda.Length > 0)
                ParametrosDeBusqueda = ParametrosDeBusqueda.Substring(0, ParametrosDeBusqueda.Length - 1);

            //HttpContext.Session["SessionParametrosDeBusqueda"] = ParametrosDeBusqueda;

            return View(ModeloTmp);
        }

        //
        // GET: /SolicitudDeInformacion/Details/5
        public ActionResult Details(int id = 0)
        {
            SolicitudesDeInformacionModel ModeloTmp = new SolicitudesDeInformacionModel();

            TMasSolInfoCedulas tmassolinfocedulas = null;// db.TMasSolInfoCedulas.Single(t => t.IdInfoSol == id);
            ModeloTmp.TMASSOLINFOCEDULAS = tmassolinfocedulas;
            //db.SPMasSolInfoRelacionNormalizar(id);
            ModeloTmp.ResultadoListaSolInfoRelacionSP = ModeloTmp.SolInfoRelacionInsertarSP_Result(id);

            if (tmassolinfocedulas == null)
            {
                return ViewBag("HttpNotFound");
            }

            List<BuscaCargaImagenesTipo_Result> ListaImagenesTmp = new List<BuscaCargaImagenesTipo_Result>();
            ListaImagenesTmp = null;// FunProc.ObtieneListaCargaImagenesTipo(tmassolinfocedulas.IdInfoSol.ToString(), "", "SOLICITUDES DE INFORMACION");
            //Session["SessionImagenesSolInfo"] = ListaImagenesTmp;

            return View(ModeloTmp);
        }

        //
        // GET: /SolicitudDeInformacion/Create
        public ActionResult Create()
        {
            //if (Session["idsvehi"] is null)
            //{
            //    Session["idsvehi"] = db.BuscaResultadoGenericoSP("nombre_rnpBarco").Select(c => c.Resultado).ToList<string>();
            //}

            //Session["Identificador"] = 0;

            //ViewBag.ofp = FunProc.LlenarResultadoGenerico("responsableofp");
            //ViewBag.asunto = FunProc.LlenarResultadoGenerico("asunto");
            //ViewBag.medio = FunProc.LlenarResultadoGenerico("medioMAS");
            //ViewBag.estado = FunProc.LlenarResultadoGenerico("estadosolinfo");
            //ViewBag.ciudad = FunProc.BuscaResultadoGenericoConParametrosLista("CIUDAdsolinfo", "", "");
            ViewBag.EmbarcacionesNombreRNP = ObtenerEmbarcacionesNombreRNP();

            SolicitudesDeInformacionModel ModeloTmp = new SolicitudesDeInformacionModel();
            ModeloTmp.fecha = DateTime.Now;
            ModeloTmp.hora = DateTime.Now.TimeOfDay.ToString().Substring(0, 8);
            ModeloTmp.folio = "PENDIENTE";
            ModeloTmp.ErroresAgregarEmbarcacion = "";

            ModeloTmp.ResultadoListaSolInfoRelacionSPTMP = ModeloTmp.SolInfoRelacionInsertarTMPSP_Result(ModeloTmp.identrada);

            return View(ModeloTmp);
        }

        //
        // POST: /SolicitudDeInformacion/Create
        [HttpPost]
        public ActionResult Create(SolicitudesDeInformacionModel ModeloTmp, string submitButton, string Estado, string opcionesbusqueda, string txtvalor, string txtvalorsolicitante, string txtciudad, string txtestado, string txtdependencia, string txtIdSel, string txtRnpSel)
        {
            //ViewBag.ofp = FunProc.LlenarResultadoGenerico("responsableofp");
            //ViewBag.asunto = FunProc.LlenarResultadoGenerico("asunto");
            //ViewBag.medio = FunProc.LlenarResultadoGenerico("medioMAS");
            //ViewBag.estado = FunProc.LlenarResultadoGenerico("estadosolinfo");
            //ViewBag.ciudad = FunProc.BuscaResultadoGenericoConParametrosLista("CIUDADsolinfo", "", Estado);
            ViewBag.EmbarcacionesNombreRNP = ObtenerEmbarcacionesNombreRNP();
            ModeloTmp.ResultadoListaSolInfoRelacionSPTMP = ModeloTmp.SolInfoRelacionInsertarTMPSP_Result(ModeloTmp.identrada);

            switch (submitButton)
            {

MASCore/MASCore/Views/SolicitudDeInformacion/BuscaSolInfo.cshtml
@model MASCore.Models.SolicitudDeInformacionEntradaDatosBusqueda

@{
    ViewBag.Title = "Búsqueda Solicitudes de Información";
}
<head>

    <script src="~/js/SolicitudDeInformacion/BuscaSolInfot.js"></script>

</head>

<article>
    <h1>Buscar Solicitudes de Información</h1>
</article>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h4>Criterios de consulta</h4>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="row">
                    <table style="width: 100%; margin-left: 15px; margin-right: 15px;">
                        <tr style="height: 50px;">
                            <td style="width: 100%;">
                                <div id="Asunto"></div>
                               
                            </td>
                        </tr>
                    </table>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <table style="width: 100%">
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="FechaInicial"></div>
                                    <div id="ToolTip1">Fecha Inicial</div>


                                </td>
                            </tr>
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="Solicitante"></div>
                                  
                                </td>
                            </tr>
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="OFP"></div>
                                   
                                </td>
                            </tr>
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="Medio"></div>
                                                                  
                                </td>
                            </tr>
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="Barco"></div>
                                  </td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <table style="width: 100%">
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="FechaFinal"></div>
                                    <div id="ToolTip2">Fecha Final</div>
                                  
                                </td>
                            </tr>
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="Folio"></div>
                              
                                </td>
                            </tr>
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="Dependencia"></div>
                                 </td>
                            </tr>
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="Estado"></div>
                              
                                </td>
                            </tr>
                            <tr style="height: 50px;">
                                <td style="width: 100%;">
                                    <div id="Ciudad"></div>
                                    @*@(Html.DevExtreme()
                                                        .SelectBoxFor(model => model.Ciudad)
                                                        .DisplayExpr("Resultado")
                                                        .ValueExpr("Resultado")
                                                        .Placeholder("-- Seleccione la Ciudad --")
                                                        .Width("100%")
                                                        .ID("Ciudad")
                                                        //.DataSource(d => d.Mvc().LoadAction("GetCiudades"))
                                                        .ElementAttr("class", "form-control")
                                                        .ShowClearButton(true)
                                    )*@
                                
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div style="text-align: right">
    <div id="search"></div>
    @*@(Html.DevExtreme()
                        .Button()
                        .Icon("fas fa-search")
                        .Type(ButtonType.Default)
                        .StylingMode(ButtonStylingMode.Contained)
                        .UseSubmitBehavior(true)
    )*@
</div>
<br />
<section>
  
        <script type="text/javascript">
                function Exportar() {
                    window.open("@Url.Action("GeneraReporteSolicitudDeInformacionExportarBusqueda", "SolicitudDeInformacion")", '_blank');
                }

                function PDF() {
                    window.open("@Url.Action("GeneratePdfSolicitudDeInformacion", "SolicitudDeInformacion")", '_blank');
                }
        </script>

        <div style="text-align: right; margin-top:5px;margin-bottom:5px;">
            <div class="row">
                <div class="col-lg-10"></div>
                <div class="col-lg-1">
                    <div id="exportToExcel"></div>
                    <div id="ToolTip4"></div>
                    
                </div>
                <div class="col-1">
                    <div id="exportToPDF"></div>
                    <div id="ToolTip5"></div>
  
                </div>
            </div>


        </div>
        <div id="grid" style="margin-top: 10px;">
            <div id="BuscaSolicitudesDeInformacion"></div>
            @*@(Html.DevExtreme()
                                .DataGrid<MASCore.BuscaSolicitudesDeInformacion_Result>()
                                .ID("gridContainer")
                                .DataSource(Model.ResultadoListaSolInfoSP, new string[] { "Folio" })
                                .ColumnHidingEnabled(true)
                                .ShowColumnLines(true)
                                .ShowRowLines(true)
                                .RowAlternationEnabled(true)
                                .ShowBorders(true)
                                .Pager(p => p.AllowedPageSizes(new int[] { 5, 8, 15, 30 })
                                .ShowInfo(true)
                                .ShowNavigationButtons(true)
                                .ShowPageSizeSelector(true)
                                .Visible(true))
                                .Paging(p => p.PageSize(5))
                                .ShowColumnHeaders(true)
                                .WordWrapEnabled(true)
                                .Columns(columns =>
                                    {
                                        columns.AddFor(m => m.Folio).Caption("Folio").Width(125);
                                        columns.AddFor(m => m.Fecha).Caption("Fecha").Format(Format.ShortDate);
                                        columns.AddFor(m => m.Solicitante).Caption("Solicitante");
                                        columns.AddFor(m => m.Cargo).Caption("Cargo");
                                        columns.AddFor(m => m.NoTotalBarcos).Caption("NoTotalBarcos");
                                        columns.AddFor(m => m.Telefono).Caption("Teléfono");
                                        columns.AddFor(m => m.Ciudad).Caption("Ciudad");
                                        columns.AddFor(m => m.Estado).Caption("Estado");
                                        columns.AddFor(m => m.Asunto).Caption("Asunto");
                                        columns.AddFor(m => m.Dependencia).Caption("Dependencia");
                                        columns.AddFor(m => m.Medio).Caption("Medio");
                                        columns.AddFor(m => m.OFP).Caption("OFP");
                                        columns.AddFor(m => m.idInfoSol).Caption("Acción").CellTemplate(@<text><a title="Ver Detalle" href='Details/<%= value %>'><i class="dx-icon far fa-folder tamanoIconoEnGrid"></i></a></text>);
                                                                    }
                                                                                                )
            )*@
        </div>
        <br />
        <br />
    
</section>

MASCore/MASCore/Views/SolicitudDeInformacion/CrearSolInfo.cshtml
@model MASCore.Models.SolicitudesDeInformacionModel

@{
    ViewBag.Title = "Nueva Solicitud de Información";

    //int identificador = (Session["Identificador"] == null
    //    ? (int)0
    //    : (int)Session["Identificador"]);      
}

<script src="~/Scripts/jquery.autocomplete.min.js" type="text/javascript"></script>
<link href="~/Content/jquery.autocomplete.css" rel="stylesheet" type="text/css" />

<div id="titulo">
    <h3 style="color:#0F2C48;text-align:center" ><u>-  Modulo Nueva Solicitud de Información  -</u></h3>        
</div>
<div style="text-align:center; color:Red;font-size:medium">
    @ViewBag.NoValidoPor
</div>

<div id="tabs">
    <div class="caption">API</div>
    <div class="tabs-container"></div>
    <div class="content  dx-fieldset">
        <div class="dx-field">
            <div class="dx-field-label">Selected index:</div>
            <div class="dx-field-value">
                <div id="selectbox">
                </div>
            </div>
        </div>
        <div class="dx-field">
            <div class="dx-field-label">Selected content:</div>
            <div class="dx-field-value-static left-aligned">
                User tab content
            </div>
        </div>
    </div>
</div>

MASCore/MASCore/Views/SolicitudDeInformacion/Delete.cshtml
@model MASCore.ModelReference.TMasSolInfoCedulas

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TMasSolInfoCedulas</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hora)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hora)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Solicitante)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Solicitante)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Cargo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Cargo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Telefono)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Telefono)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Ciudad)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ciudad)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Estado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Estado)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Asunto)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Asunto)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Dependencia)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Dependencia)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Medio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Medio)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descripcion)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OFP)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OFP)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Folio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Folio)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MASCore/MASCore/Views/SolicitudDeInformacion/Index.cshtml
@{
    ViewBag.Title = "Opciones Solicitudes de Información";
}

<style>
    .panel {
        margin-bottom: 20px;
        background-color: #2A3F54;
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
        color: white;
    }

    a, a:hover {
        color: #CDA434;
    }
</style>
<div class="index">
    <article>
        <h1>Módulo Solicitudes de Información</h1>
    </article>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h4>Panel de Opciones</h4>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="panel">
                                <div class="panel-heading" style="min-height: 75px; max-height: 75px;">
                                    <div class="row">
                                        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                            <i class="fas fa-search fa-1x"></i>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 text-center">
                                            <div><h6>Buscar Solicitudes de Información </h6></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body" style="background-color:#f5f5f5;color:black">
                                    <p>Ingresando al módulo podrá ver los detalles, editar,imprimir y/o exportar la Solicitud De Información encontrada.</p>
                                </div>
                                <a href='@Url.Action("BuscaSolInfo", "SolicitudDeInformacion")'>
                                    <div class="panel-footer" style="min-height: 40px; max-height: 40px;">
                                        <div class="text-right">
                                            <i id="ir2" class="fa fa-arrow-circle-right tamanoIconoEnGrid"></i>
                                            
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="panel">
                                <div class="panel-heading" style="min-height: 75px; max-height: 75px;">
                                    <div class="row">
                                        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                            <i class="fas fa-file-alt fa-1x"></i>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 text-center">
                                            <div><h6>Crear Nueva Solicitud de Información </h6></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body" style="background-color:#f5f5f5;color:black">
                                    <p>Opción para crear una nueva Solicitud De Información.</p>
                                </div>
                                <a href='@Url.Action("Create", "SolicitudDeInformacion")'>
                                    <div class="panel-footer" style="min-height: 40px; max-height: 40px;">
                                        <div class="text-right">
                                            <i id="ir1" class="fa fa-arrow-circle-right tamanoIconoEnGrid"></i>
                                            
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
</div>