MASCore/MASCore/Controllers/ReportesAvanzadosController.cs
using ClosedXML.Excel;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using MASCore.Components;
using MASCore.Exportar;
using MASCore.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Configuration; 
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;





namespace MASCore.Controllers
{
    public class ReportesAvanzadosController : Controller
    {
        private BDMasContextEnt db = new BDMasContextEnt();
        FuncionesProcedimientos FunProc = new FuncionesProcedimientos();



        string Nota = "Nota importante: De conformidad con los artículos de la Ley Federal de la Trasparencia y Acceso a la Información Pública Gubernamental, y lineamientos Trigésimo Séptimo de los Lineamientos Generales ";
        string Nota2 = "para la clasificación y desclasificación de información de las Dependencias Públicas Gubernamentales de la Administración Pública Federal, la información relacionada con el Sistema de Localización ";
        string Nota3 = "y Monitoreo Satelital de Embarcaciones Pesqueras de la Dirección General de Inspección y Vigilancia de la CONAPESCA, contenida  en este mensaje electrónico o anexa al mismo, es considerada como ";
        string Nota4 = "reservada o confidencial, por lo que cualquier uso, reproducción, difusión o distribución ya sea total o parcial de este mensaje y sus anexos está estrictamente prohibida. Si usted ha recibido ";
        string Nota5 = "esta transmisión por error, por favor notifique al remitente inmediatamente a vuelta de correo electrónico y borrar este mensaje y sus anexos; en caso de incumplimiento, además de las responsabilidades ";
        string Nota6 = "administrativas que se generen, podrá ser sujeto de las acciones civiles y/o penales que procedan. Lo anterior conforme a los artículos 210,211, 211 Bis, 211 Bis 1, 211 Bis 2, 211 Bis 3, 211 Bis 4 y ";
        string Nota7 = "de más relativos al Código Penal Federal.";
        string NotaCompleta = "Nota importante: De conformidad con los artículos de la Ley Federal de la Trasparencia y Acceso a la Información Pública Gubernamental, y lineamientos Trigésimo Séptimo de los Lineamientos Generales para la clasificación y desclasificación de información de las Dependencias Públicas Gubernamentales de la Administración Pública Federal, la información relacionada con el Sistema de Localización y Monitoreo Satelital de Embarcaciones Pesqueras de la Dirección General de Inspección y Vigilancia de la CONAPESCA, contenida  en este mensaje electrónico o anexa al mismo, es considerada como reservada o confidencial, por lo que cualquier uso, reproducción, difusión o distribución ya sea total o parcial de este mensaje y sus anexos está estrictamente prohibida. Si usted ha recibido esta transmisión por error, por favor notifique al remitente inmediatamente a vuelta de correo electrónico y borrar este mensaje y sus anexos; en caso de incumplimiento, además de las responsabilidades administrativas que se generen, podrá ser sujeto de las acciones civiles y/o penales que procedan. Lo anterior conforme a los artículos 210,211, 211 Bis, 211 Bis 1, 211 Bis 2, 211 Bis 3, 211 Bis 4 y de más relativos al Código Penal Federal.";

        // GET: /ReportesAvanzados/
        public ActionResult Index()
        {

            string UserName = "";
            if (HttpContext.Request.Cookies["userName"] != null)
                UserName = HttpContext.Request.Cookies["userName"].ToString();
            ViewBag.Valida7X24 = FunProc.ValidaPermisoUsuario7X24(UserName); //User.Identity.Name
            return View();
        }


        #region "MODULO DE CAPTURA ACTIVIDADES DE OPERADORES"
        public class CapturaActividadesM
        {
            [DisplayName("Turno:")]
            public String Turno { get; set; }
            [DisplayName("Usuario:")]
            public String Usuario { get; set; }
            [DisplayName("Fecha:")]
            public String Fecha { get; set; }
            [Range(0, 23)]
            [DisplayName("Hora:")]
            public String Hora { get; set; }
            [Range(1, 59)]
            [DisplayName("Minutos:")]
            public String Minutos { get; set; }

            [DisplayName("Usuario Astrum:")]
            public String usuarioastrum { get; set; }

            [DisplayName("Comentarios:")]
            public String Comentarios { get; set; }
        }
        #endregion


    }
}    

MASCore/MASCore/Views/ReportesAvanzados/CapturaActividades.cshtml
@model MASCore.Models.CapturaActividadesM

@{
    ViewBag.Title = "Captura de Actividades";
}

<article>
    <h1>Captura de Actividades de Operadores</h1>
</article>

@if (!string.IsNullOrEmpty(ViewBag.NoValidoPor))
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.NoValidoPor
    </div>
}



@*@using (Html.BeginForm()) *@
@using (Html.BeginForm("CapturaActividades", "ReportesAvanzados", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                @*<div class="x_title">
                        <h4>Criterios de consulta</h4>
                        <div class="clearfix"></div>
                    </div>*@
                <div class="x_content">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @Html.LabelFor(model => model.Turno)
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @(Html.DevExtreme().SelectBoxFor(o => o.Turno)
                                                      .DataSource(ViewBag.turno)
                                                      .DisplayExpr("Resultado")
                                                      .ValueExpr("Resultado")
                                                      .Width("100%")
                                                      .ElementAttr("class", "form-control")
                                                      .ShowClearButton(true))
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @Html.LabelFor(model => model.Usuario)
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @(Html.DevExtreme().TextBoxFor(o => o.Usuario)
                                                      .Width("100%")
                                                      .ElementAttr("class", "form-control")
                                                      .ShowClearButton(true))
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @Html.LabelFor(model => model.Fecha)
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @(Html.DevExtreme().DateBoxFor(o => o.Fecha)
                                                      .Width("100%")
                                                      .ElementAttr("class", "form-control")
                                                      .ShowClearButton(true))
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @Html.LabelFor(model => model.usuarioastrum)
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @(Html.DevExtreme().SelectBoxFor(o => o.usuarioastrum)
                                                      .DataSource(ViewBag.usuarioastrum)
                                                      .DisplayExpr("Resultado")
                                                      .ValueExpr("Resultado")
                                                      .Width("100%")
                                                      .ElementAttr("class", "form-control")
                                                      .ShowClearButton(true))
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @Html.LabelFor(model => model.Hora)
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @(Html.DevExtreme().SelectBoxFor(o => o.Hora)
                                                      .DataSource(ViewBag.Hora)
                                                      .DisplayExpr("Resultado")
                                                      .ValueExpr("Resultado")
                                                      .Width("100%")
                                                      .ElementAttr("class", "form-control")
                                                      .ShowClearButton(true))
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @Html.LabelFor(model => model.Minutos)
                                    </div>
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @(Html.DevExtreme().SelectBoxFor(o => o.Minutos)
                                                      .DataSource(ViewBag.Minutos)
                                                      .DisplayExpr("Resultado")
                                                      .ValueExpr("Resultado")
                                                      .Width("100%")
                                                      .ElementAttr("class", "form-control")
                                                      .ShowClearButton(true))
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-3" style="padding-right: 0; padding-top: 16px;">
                                        @Html.LabelFor(model => model.Comentarios)
                                    </div>
                                    <div class="col-9" style="padding-right: 0; padding-top: 16px;">
                                        @(Html.DevExtreme().TextAreaFor(o => o.Comentarios)
                                              .Width("100%")
                                              .ElementAttr("class", "form-control"))
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-11"></div> @*offset-10*@
                                    <div class="col-1" style="padding-right: 0; padding-top: 16px;">
                                        @(Html.DevExtreme().Button().ID("btnSubmit").Icon("fas fa-save").Text("").UseSubmitBehavior(true).Type(ButtonType.Default).Width("100%"))
                                        @(Html.DevExtreme().Tooltip().Target("#btnSubmit").ShowEvent("mouseenter").HideEvent("mouseleave").ContentTemplate("Guardar Información"))
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Regresar a Reportes Avanzados", "Index")
</div>*@
<script type="text/javascript">
    $("#btnSubmit").attr("name", "submitButton").vañ("Guardar")
</script>

MASCore/MASCore/Views/ReportesAvanzados/GeneraReporteActividadOperadoresPdf.cshtml
@model List< MASCore.Models.ReporteActividadOperadoresList>

@{
    Layout = "~/Views/Shared/_PdfLayout.cshtml";
    string ParametrosDeBusqueda = "";
    ParametrosDeBusqueda = Session["SessionParametrosDeBusqueda"] as string;

}


<table width="100%" cellpadding="1.0" cellspacing="1.0"   widths="1;4;1">
    <row>
        <cell >   <image url="@Context.Server.MapPath("~/Content/Logo1.jpg")"/>     </cell>
        <cell horizontalalign="Default" verticalalign="Default">
            <paragraph style="font-size: 13;font-weight:normal;" red="60" green="60" blue="60" align="Center">
                COMISION NACIONAL DE ACUACULTURA Y PESCA <br />
                DIRECCIÓN GENERAL DE INSPECCION Y VIGILANCIA <br />
            </paragraph>
            <chunk style="font-size: 13;font-weight:normal" red="60" green="60" blue="60" align="Center">  DIRECCIÓN DE MONITOREO Y COORDINACIÓN</chunk> 
        </cell>
        <cell>   <image url="@Context.Server.MapPath("~/Content/Logo2.jpg")"/>     </cell>
    </row>
    
</table>

<paragraph style="font-family: Helvetica; font-size: 16; "  align="Center">
	<chunk style="font-weight:normal;" red="60" green="60" blue="60">REPORTE - BITACORA DE ACTIVIDADES</chunk>
</paragraph>

<table width="100%" cellpadding="1.0" cellspacing="1.0"   widths="3;3;2">
    <row>
        <cell colspan="2"> Impreso por: @Html.Encode(Request.Cookies["userName"].Value.ToUpper()) </cell>
        @*<cell></cell>*@
        <cell> Fecha: @DateTime.Now.Date.ToShortDateString()  </cell>
    </row>
    <row>
        <cell colspan="3">
            @ParametrosDeBusqueda
        </cell>
    </row>
</table>

@if (Model != null && Model.Count > 0)
{



<table width="100%" cellpadding="1.0" cellspacing="1.0"  border="2" widths="2.3;1;1;1;.7" red="255" green="255" blue="255">  
    <row>
	    <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" header="true" leading="18.0">            	         
             <chunk style="font-family: Helvetica; font-size: 10;font-weight:bold;"  red="10" green="100" blue="100">
                Operador
            </chunk>             
        </cell>	   
	    <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >
            <chunk style="font-family:Helvetica;font-size: 10;font-weight:bold;"  red="10" green="100" blue="100">
                Fecha
            </chunk>
        </cell>
	    <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >
            <chunk style="font-family:Helvetica;font-size: 10;font-weight:bold;"  red="10" green="100" blue="100">
                Actividad
            </chunk>
        </cell>
        <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >
            <chunk style="font-family:Helvetica;font-size: 10;font-weight:bold;"  red="10" green="100" blue="100">
                Tipo
            </chunk>
        </cell>
        <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >
            <chunk style="font-family:Helvetica;font-size: 10;font-weight:bold;"  red="10" green="100" blue="100">
                Id
            </chunk>
        </cell>     
    </row>
    @foreach (var item in Model)
    {
        string Fecha = "";
        if (@item.Fecha != null)
        {
            Fecha = @item.Fecha.PadLeft(10, ' ').Substring(0, 10);
        }
    <row>
	    
	    <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >    @*red="255" green="0" blue="0"*@
            <chunk style="font-family:Helvetica;font-size: 9;">
                @Html.DisplayFor(modelItem => item.Operador)
            </chunk>
        </cell>
	    <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >
            <chunk style="font-family:Helvetica;font-size: 9;">
                @Fecha
            </chunk>
        </cell>
        <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >
            <chunk style="font-family:Helvetica;font-size: 9;">
                @Html.DisplayFor(modelItem => item.Actividad)
            </chunk>
        </cell>
        <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >
            <chunk style="font-family:Helvetica;font-size: 9;">
                @Html.DisplayFor(modelItem => item.Tipo)
            </chunk>
        </cell>                       
        <cell borderwidth="0.5" left="true" right="true" top="true" bottom="true" >
            <chunk style="font-family:Helvetica;font-size: 9;">
                @Html.DisplayFor(modelItem => item.Id)
            </chunk>
        </cell>        
    </row>
    }
</table>

}

MASCore/MASCore/Views/ReportesAvanzados/MarcadoresEarthPageTabularRepEstadistico.cshtml
@model MASCore.Models.MarcadoresEarthModelRepEstadistico

@{
    Layout = "~/Views/Shared/_LayoutSimple.cshtml";
    ViewBag.Title = "Detalle Reporte Diario";
}

<h4>Distribución de cedulas por situación</h4>

<div class="row col-12">
    <div class="col-6">
        <div class="dx-field row">
            <div class="dx-field-label col-5">Fecha:</div>
            <div class="dx-field-label col-7">
                @DateTime.Now.ToShortDateString()
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="dx-field row">
            @{
                if (Model.Reporte.Equals("EMERGENCIA"))
                {
                    <div class="dx-field-label col-5">Situación:</div>
                    <div class="dx-field-label col-7">EMERGENCIA</div>
                }
                else
                {
                    <div class="dx-field-label col-5">Litoral:</div>
                    <div class="dx-field-label col-7">@Model.Litoral</div>
                }
            }
        </div>
    </div>
</div>
<div class="row col-12">
    <div class="col-6">
        <div class="dx-field row">
            @{
                if (Model.Reporte.Equals("EMERGENCIA"))
                {
                    <div class="dx-field-label col-5">Causa:</div>
                    <div class="dx-field-label col-7">@Model.Litoral</div>
                }
                else
                {
                    <div class="dx-field-label col-5">Situación:</div>
                    <div class="dx-field-label col-7">@Model.Reporte</div>
                }
            }
        </div>
    </div>
    <div class="col-6">
        <div class="row">
            <div class="col-1">
                <script type="text/javascript">
                    var url = '@Url.Action("GeneraReporteMarcadoresEarthPageTabularRepEstadistico", "ReportesAvanzados")';
                    function download() {
                        window.open(url, "_blank");
                    }
                </script>
                <a href='javascript:download();' class="btn btn-outline-secondary"><i class="fas fa-cloud-download-alt fa-2x"></i></a>
            </div>
            <div class="col-1">
                <a href="javascript:window.print();" class="btn btn-outline-secondary"><i class="fas fa-print fa-2x"></i></a>
            </div>
            <div class="col-10"></div>
        </div>
    </div>
</div>

@(Html.DevExtreme().DataGrid<MASCore.ObtieneMarcadoresDetalleAlertasCedulas_Result>()
        .DataSource(Model.ListaMarcadoresTabular)
        .ShowColumnLines(true)
        .ShowRowLines(true)
        .RowAlternationEnabled(true)
        .ShowBorders(true)
        .ShowColumnHeaders(true)
        .WordWrapEnabled(true)
        .Columns(columns =>
        {
            columns.AddFor(m => m.Matricula).Caption("Matricula").AllowSorting(false);
            columns.AddFor(m => m.Embarcacion).Caption("Embarcación").AllowSorting(false);
            columns.AddFor(m => m.RNP).Caption("RNP").AllowSorting(false);
            columns.AddFor(m => m.RazonSocial).Caption("Razón Social").AllowSorting(false);
            columns.AddFor(m => m.PuertoBase).Caption("Puerto Base").AllowSorting(false);
            columns.AddFor(m => m.Estado).Caption("Estado").AllowSorting(false);
            columns.AddFor(m => m.Causas).Caption("Causa").AllowSorting(false);
            columns.AddFor(m => m.Fecha).Caption("Fecha Evento").AllowSorting(false).Format("dd/MM/yyyy");
        })
)

MASCore/MASCore/Views/ReportesAvanzados/ReporteDentroYFueraPuerto.cshtml
@model MASCore.Models.ReporteDentroYFueraPuertoM

@{
    /**/

    ViewBag.Title = "Reporte Embarcaciones dentro y fuera de puerto";
}

@using (Html.BeginForm("ReporteDentroYFueraPuerto", "ReportesAvanzados", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <article>
        <h1>Reporte Embarcaciones dentro y fuera de puerto</h1>
    </article>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h4>Criterios de consulta</h4>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="row">
                        <div class="col-4">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-6" style="padding-right: 0;padding-top: 5px;">
                                        @(Html.DevExtreme().SwitchFor(model => model.TodosBol).ID("TodosBol").OnValueChanged("sumarizacion_checked").Width("40%").ElementAttr("class", "form-control"))
                                    </div>
                                    <div class="col-6" style="padding-top:8px">
                                        @Html.LabelFor(model => model.TodosBol)
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-5" style="padding-right: 0;padding-top: 5px;">
                                        @(Html.DevExtreme().SwitchFor(model => model.DentroPuerto).ID("DentroPuerto").Width("50%").ElementAttr("class", "form-control"))
                                    </div>
                                    <div class="col-7" style="padding-top:8px">
                                        @Html.Label("Dentro de Puerto")
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-5" style="padding-right: 0;padding-top: 5px;">
                                        @(Html.DevExtreme().SwitchFor(model => model.FueraPuerto).ID("FueraPuerto").Width("50%").ElementAttr("class", "form-control"))
                                    </div>
                                    <div class="col-7" style="padding-top:8px">
                                        @Html.Label("Fuera de Puerto")
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="row">
                                <div class="col-3" style="padding-right:0;padding-top:7px">
                                    @(Html.DevExtreme().SwitchFor(model => model.EmbarcacionBol).ID("swEmbarcacion").OnValueChanged("sumarizacion_checked").Width("50%").ElementAttr("class", "form-control"))
                                </div>
                                <div class="col-9" style="padding-left:2px;padding-right:0">
                                    @(Html.DevExtreme().AutocompleteFor(model => model.Embarcacion).MinSearchLength(1).DataSource(d => d.Mvc().LoadAction("SearchResultadoGenerico_matriculanombrernp2")).Placeholder("Embarcación").Width("100%").ID("MatriculaEmbarcacionRNP").ElementAttr("class", "form-control").ShowClearButton(true))
                                    
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="row">
                                <div class="col-3" style="padding-right:0;padding-top:7px">
                                    @(Html.DevExtreme().SwitchFor(model => model.GrupoBol).ID("swGrupo").Width("50%").OnValueChanged("sumarizacion_checked").ElementAttr("class", "form-control"))
                                </div>
                                <div class="col-9" style="padding-left:2px;padding-right:0">
                                    @(Html.DevExtreme().SelectBoxFor(model => model.Grupo).DataSource(ViewBag.Grupo).Placeholder("-- Seleccione un Grupo --").DisplayExpr("Resultado").ValueExpr("Resultado").Width("100%").ID("Grupo").ElementAttr("class", "form-control").ShowClearButton(true))
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="text-align: right">
        <script>
            var pdf = '@Url.Action("GeneraReporteDentroYFueraPuertoPdf", "ReportesAvanzados")';
            var xls = '@Url.Action("GeneraReporteDentroYFueraPuerto", "ReportesAvanzados")';
            var urlComback = '@Url.Action("Index", "ReportesAvanzados")';
        </script>
        <div class="col-10"></div>
        <div class="col-1" style="padding-right:0">
            @(Html.DevExtreme().Button().ID("btnConsulta").Icon("fas fa-search").Type(ButtonType.Default).StylingMode(ButtonStylingMode.Contained).UseSubmitBehavior(true))
            @(Html.DevExtreme().Tooltip().Target("#btnConsulta").ContentTemplate(@<text>Consultar información</text>).ShowEvent("mouseenter").HideEvent("mouseleave"))
        </div>
        <div class="col-1" style="padding-left:0;text-align: center;">
            @(Html.DevExtreme().Button().ID("btnAtras").Icon("fas fa-undo-alt").Type(ButtonType.Default).StylingMode(ButtonStylingMode.Contained).UseSubmitBehavior(false).OnClick(@"function(args){comback(urlComback)}"))
            @(Html.DevExtreme().Tooltip().Target("#btnAtras").ContentTemplate(@<text>Regresar a la página anterior</text>).ShowEvent("mouseenter").HideEvent("mouseleave"))

        </div>
    </div>
    <div>
        @if (Model.InfoDentroYFueraPuertoLista.Count() > 0)
        {
            <div class="row" style="text-align: right;padding-top: 5px;padding-bottom: 5px;">
                <div class="col-10"></div>
                <div class="col-1" style="padding-right: 0;">
                    @(Html.DevExtreme().Button().Icon("fas fa-file-excel").Type(ButtonType.Default).StylingMode(ButtonStylingMode.Contained).UseSubmitBehavior(false).OnClick(@"function(args){comback(xls)}"))
                </div>
                <div class="col-1" style="padding-left:0;text-align:center;">
                    @(Html.DevExtreme().Button().Icon("fa fa-file-pdf").Type(ButtonType.Default).StylingMode(ButtonStylingMode.Contained).UseSubmitBehavior(false).OnClick(@"function(args){ExportarPDF(pdf)}"))
                </div>
            </div>

            @(Html.DevExtreme().DataGrid<MASCore.Models.InformacionDentroYFueraPuerto>()
                .DataSource(Model.InfoDentroYFueraPuertoLista).ColumnHidingEnabled(true)
                .ShowColumnLines(true).ShowRowLines(true).RowAlternationEnabled(true).ShowBorders(true)
                .Pager(p => p.AllowedPageSizes(new int[] { 5, 8, 15, 30 })
                    .ShowInfo(true).ShowNavigationButtons(true).ShowPageSizeSelector(true).Visible(true))
                .Paging(p => p.PageSize(10)).ShowColumnHeaders(true).WordWrapEnabled(true)
                .Columns(columns => {
                    columns.AddFor(m => m.embarcacion).Caption("Embarcación");
                    columns.AddFor(m => m.puerto).Caption("Puerto");
                    columns.AddFor(m => m.propietario).Caption("Propietario");
                    columns.AddFor(m => m.matricula).Caption("Matricula");
                    columns.AddFor(m => m.RNP).Caption("RNP");
                    columns.AddFor(m => m.fecha).Caption("Fecha");
                    columns.AddFor(m => m.enpuerto).Caption("Estatus");
                })
            )
        }
    </div>

    <script>
        function sumarizacion_checked(data) {
            console.log(data)
            switch (data.element[0].id) {
                default: break;
                case "TodosBol":
                    if ($("#TodosBol").dxSwitch("instance").option("value")) {
                        $("#swEmbarcacion").dxSwitch("instance").option({ "value": false });
                        $("#swGrupo").dxSwitch("instance").option({ "value": false });
                    }
                    break;
                case "swEmbarcacion":
                    if ($("#swEmbarcacion").dxSwitch("instance").option("value")) {
                        $("#TodosBol").dxSwitch("instance").option({ "value": false });
                        $("#swGrupo").dxSwitch("instance").option({ "value": false });
                    }
                    break;
                case "swGrupo":
                    if ($("#swGrupo").dxSwitch("instance").option("value")) {
                        $("#swEmbarcacion").dxSwitch("instance").option({ "value": false });
                        $("#TodosBol").dxSwitch("instance").option({ "value": false });
                    }
                    break;
            }
        }
    </script>
}