MASCore/MASCore/Controllers/LlamadasController.cs
using ClosedXML.Excel;
using DevExtreme.AspNet.Data;
using MASCore.Components;
using MASCore.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using Xceed.Words.NET;
using MASCore.DataModel;
using DataSourceLoadOptions = DevExtreme.AspNet.Mvc.DataSourceLoadOptions;
using MASCore.ModelReference;
using BuscaLlamadas_Result = MASCore.DataModel.BuscaLlamadas_Result;
using Microsoft.AspNetCore.Http;
using System.IO;
using MASCore.Exportar;

namespace MASCore.Controllers
{
    public class LlamadasController : Controller
    {
        //private BDMasContextEnt db = new BDMasContextEnt();
        FuncionesProcedimientos FunProc = new FuncionesProcedimientos();

        #region Cargar Combos
        [HttpGet]
        public ActionResult GetActividades(DataSourceLoadOptions loadOptions)
        {
            return null;// Content(JsonConvert.SerializeObject(DataSourceLoader.Load(FunProc.LlenarResultadoGenerico("btactividades"), loadOptions)), "application/json");
        }

        [HttpGet]
        public ActionResult GetResponsablesOFP(DataSourceLoadOptions loadOptions)
        {
            return null;// Content(JsonConvert.SerializeObject(DataSourceLoader.Load(FunProc.LlenarResultadoGenerico("responsableofp"), loadOptions)), "application/json");
        }

        [HttpGet]
        public ActionResult GetFiltros(DataSourceLoadOptions loadOptions)
        {
            return null;//Content(JsonConvert.SerializeObject(DataSourceLoader.Load(FunProc.LlenarResultadoGenerico("filtro"), loadOptions)), "application/json");
        }

        [HttpGet]
        public ActionResult GetOpcionesBusqueda(DataSourceLoadOptions loadOptions)
        {
            return null;//Content(JsonConvert.SerializeObject(DataSourceLoader.Load(FunProc.LlenarResultadoGenerico("opcionesbusqueda"), loadOptions)), "application/json");
        }

        [HttpGet]
        public ActionResult GetBTTipos(DataSourceLoadOptions loadOptions)
        {
            return null;// Content(JsonConvert.SerializeObject(DataSourceLoader.Load(FunProc.LlenarResultadoGenerico("bttipos"), loadOptions)), "application/json");
        }

        [HttpGet]
        public ActionResult GetRespuestas(DataSourceLoadOptions loadOptions)
        {
            IList<BuscaResultadoGenerico_Result> res = new List<BuscaResultadoGenerico_Result>();
            res.Add(new BuscaResultadoGenerico_Result() { Resultado = Resources.Etiquetas.SI });
            res.Add(new BuscaResultadoGenerico_Result() { Resultado = Resources.Etiquetas.NO });
            return Content(JsonConvert.SerializeObject(DataSourceLoader.Load(res, loadOptions)), "application/json");
        }
        #endregion

        // GET: /Llamadas/
        public ActionResult Index()
        {
            //return View(db.TMasBTBitaCels.ToList());
            return View();
        }
        //GET
        public ActionResult BuscaLlamada()
        {
            //string currentLang = Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName;//Thread.CurrentThread.CurrentCulture = new CultureInfo("");
            
            LlamadaBusquedaModel ModeloTmp = new LlamadaBusquedaModel();
            ModeloTmp.FechaInicial = DateTime.Now; //Convert.ToDateTime("01/01/2009");               
            ModeloTmp.FechaFinal = DateTime.Now;
            List<BuscaLlamadas_Result> Modelotemporal = new List<BuscaLlamadas_Result>();

            //ModeloTmp.ResultadoListaLlamadasSP = Modelotemporal;// ModeloTmp.EncuentraLasLlamadasSP("",ModeloTmp.FechaInicial, ModeloTmp.FechaFinal,"","","");
            //Session.Remove("SessionResultadoListaLlamadasSP");

            //ViewBag.actividad = FunProc.LlenarResultadoGenerico("btactividades");
            //ViewBag.ofp = FunProc.LlenarResultadoGenerico("responsableofp");
            //ViewBag.filtro = FunProc.LlenarResultadoGenerico("filtro");
            //Session["SessionResultadoListaLlamadasSP"] = ModeloTmp.ResultadoListaLlamadasSP;
            return View(ModeloTmp);
        }

        [HttpPost]
        public ActionResult BuscaLlamada(LlamadaBusquedaModel ModeloTmp)
        {
            List<BuscaLlamadas_Result> Modelotemporal = new List<BuscaLlamadas_Result>();
            //ModeloTmp.ResultadoListaLlamadasSP = Modelotemporal;

            #region "VALIDACIONES"
            Boolean Valido = true;
            if (ModeloTmp.FechaInicial > ModeloTmp.FechaFinal)
            {
                ViewBag.NoValidoPor = "No es posible realizar la búsqueda, la fecha inicial no puede ser mayor a la fecha final. Verificar.";
                Valido = false;
            }
            if (ModeloTmp.FechaInicial.Year < 1753 || ModeloTmp.FechaFinal.Year < 1753)
            {
                ViewBag.NoValidoPor = "No es posible realizar la búsqueda. Verificar Fechas.";
                Valido = false;
            }
            //if (ModeloTmp.Filtro == null)
            //{
            //    ViewBag.NoValidoPor = "No es posible realizar la busqueda. Debe Seleccionar un Filtro.";
            //    Valido = false;
            //}
            #endregion

            if (Valido == true)
            {            
                ModeloTmp.ResultadoListaLlamadasSP = ModeloTmp.EncuentraLasLlamadasSP(ModeloTmp.Filtro, ModeloTmp.FechaInicial, ModeloTmp.FechaFinal, ModeloTmp.Actividad, ModeloTmp.Embarcacion, ModeloTmp.Ofp);
            }

            //Session["SessionResultadoListaLlamadasSP"] = ModeloTmp.ResultadoListaLlamadasSP;

            //ViewBag.actividad = FunProc.LlenarResultadoGenerico("btactividades");
            //ViewBag.ofp = FunProc.LlenarResultadoGenerico("responsableofp");
            //ViewBag.filtro = FunProc.LlenarResultadoGenerico("filtro");

            string ParametrosDeBusqueda = "";            
            ParametrosDeBusqueda += "Desde " + ModeloTmp.FechaInicial.ToShortDateString() + " Hasta " + ModeloTmp.FechaFinal.ToShortDateString() + " |";
            if (ModeloTmp.Embarcacion != null && ModeloTmp.Embarcacion.Length > 0)
                ParametrosDeBusqueda += " Embarcacion: " + ModeloTmp.Embarcacion + " |";
            if (ModeloTmp.Actividad != null && ModeloTmp.Actividad.Length > 0)
                ParametrosDeBusqueda += " Actividad: " + ModeloTmp.Actividad + " |";
            if (ModeloTmp.Filtro != null && ModeloTmp.Filtro.Length > 0)
                ParametrosDeBusqueda += " Filtro: " + ModeloTmp.Filtro + " |";
            if (ModeloTmp.Ofp != null && ModeloTmp.Ofp.Length > 0)
                ParametrosDeBusqueda += " OFP: " + ModeloTmp.Ofp + " |";
           
            if (ParametrosDeBusqueda.Length > 0)
                ParametrosDeBusqueda = ParametrosDeBusqueda.Substring(0, ParametrosDeBusqueda.Length - 1);


            //Session["SessionParametrosDeBusqueda"] = ParametrosDeBusqueda;

            return View(ModeloTmp);
        }

        public static string EncodePassword(string originalPassword)
        {
            int nHash = originalPassword.GetHashCode();
            SHA1 sha1 = new SHA1CryptoServiceProvider();
            byte[] inputBytes = (new UnicodeEncoding()).GetBytes(originalPassword);
            byte[] hash = sha1.ComputeHash(inputBytes);

            return Convert.ToBase64String(hash);
        }   

        // GET: /Llamadas/Details/5
        public ActionResult Details(int id = 0)
        {
            if (id == 0)
            {
                return RedirectToAction("Index");
            }
            LlamadaModel ModeloTmp = new LlamadaModel();
            TMasBTBitaCel tmasbtbitacel = null;//db.TMasBTBitaCels.Single(t => t.IdBitaCel == id);
            ModeloTmp.TMASBTBITACEL = tmasbtbitacel;

            List<TMasBTControlTelefonos> ListadeTelefonos = new List<TMasBTControlTelefonos>();
            ListadeTelefonos = ModeloTmp.EncuentraLasLlamadasEnDBSP(id);
            ModeloTmp.TMASBTCONTROLTELEFONOS_LISTA = ListadeTelefonos;

            if (tmasbtbitacel == null)
            {
                return StatusCode(404);
            }

            List<BuscaCargaImagenesTipo_Result> ListaImagenesTmp = new List<BuscaCargaImagenesTipo_Result>();
            //ListaImagenesTmp = FunProc.ObtieneListaCargaImagenesTipo(tmasbtbitacel.IdBitaCel.ToString(), "", "LLAMADAS TELEFÓNICAS");
            //Session["SessionImagenesLlamadas"] = ListaImagenesTmp;

            return View(ModeloTmp);
        }
       
        // GET: /Llamadas/Create
        public ActionResult Create(LlamadaModel ModeloTmp2, string submitButton, string bttipos)
        {
            #region "Usados para la sección Llamadas"
            LlamadaModel ModeloTmp = new LlamadaModel();
            ModeloTmp.MostrandoBusquedaInformacionEmbarcacion = false;
            List<SPMASBuscaInformacionDeEmbarcacionyPangas_Result> ModeloInformacionDeEmbarcacion = new List<SPMASBuscaInformacionDeEmbarcacionyPangas_Result>();
            ModeloTmp.InformacionDeEmbarcacion = ModeloInformacionDeEmbarcacion;
            
            ModeloTmp.Identificador = "0";
            //ViewBag.opcionesbusqueda = new SelectList(FunProc.LlenarResultadoGenerico("opcionesbusqueda"), "Resultado", "Resultado");
            //ViewBag.actividad = new SelectList(FunProc.LlenarResultadoGenerico("btactividades"), "Resultado", "Resultado");
            //ViewBag.ofp = new SelectList(FunProc.LlenarResultadoGenerico("responsableofp"), "Resultado", "Resultado");
            //ViewBag.filtro = new SelectList(FunProc.LlenarResultadoGenerico("filtro"), "Resultado", "Resultado");
            //ViewBag.bttipos = new SelectList(FunProc.LlenarResultadoGenerico("bttipos"), "Resultado", "Resultado");
            //ViewBag.respuestallamada = new SelectList(FunProc.LlenarResultadoGenerico("respuestallamada"), "Resultado", "Resultado");
            //List<SelectListItem> respuestaList = new List<SelectListItem>();

MASCore/MASCore/Views/Llamadas/BuscaLlamada.cshtml
@model MASCore.Models.LlamadaBusquedaModel
@using Microsoft.AspNetCore.Http.Extensions

@using MASCore.Models

@{
    ViewBag.Title = "Módulo de Búsqueda de Llamada";
   
}
<head>
   
    <script src="~/js/Llamadas/BuscaLlamadas.js"></script>
</head>

<div style="text-align:center; color:Red;font-size:medium">
    @ViewBag.NoValidoPor
</div>

@using (Html.BeginForm("BuscaLlamada", "Llamadas", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <article>
        <h1>Buscar Llamadas</h1>
    </article>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h4>Criterios de consulta</h4>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group">
                                <div class="col-12">
                                    <div id="FechaInicial"></div>
                                    <div id="ToolTip1">Fecha Inicial</div>
                                    @*@(Html.DevExtreme().DateBoxFor(model => model.FechaInicial).DisplayFormat("dd/MM/yyyy")
                                                .Placeholder("Fecha Inicial").Width("100%").ID("FechaInicial")
                                                .ElementAttr("class", "form-control").ShowClearButton(true)
                                                .InvalidDateMessage("Fecha no valida")
                                    )
                                    @(Html.DevExtreme().Tooltip()
                                                .Target("#FechaInicial")
                                                .ShowEvent("mouseenter")
                                                .HideEvent("mouseleave")
                                                .ContentTemplate(@<text>
                                                    <b>Fecha Inicial</b>
                                                </text>)
                                    )*@
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-12">
                                    <div id="FechaFinal"></div>
                                    <div id="ToolTip2">Fecha Final</div>
                                    @*@(Html.DevExtreme().DateBoxFor(model => model.FechaFinal).DisplayFormat("dd/MM/yyyy")
                            .Placeholder("Fecha Final").ID("FechaFinal")
                            .ElementAttr("class", "form-control")
                            .ElementAttr("style", "width: 95%;margin-left: 15px;").ShowClearButton(true)
                            .InvalidDateMessage("Fecha no valida")
        )
        @(Html.DevExtreme().Tooltip()
                            .Target("#FechaFinal")
                            .ShowEvent("mouseenter")
                            .HideEvent("mouseleave")
                            .ContentTemplate(@<text>
                                <b>Fecha Final</b>
                            </text>)
        )*@
                                </div>
                            </div>
                                <div class="form-group">
                                    <div class="col-12">
                                        <div id="actividades"></div>
                                        @*@(Html.DevExtreme().SelectBoxFor(o => o.Actividad).DisplayExpr("Resultado").ValueExpr("Resultado")
                                    .Placeholder("-- Seleccione un Tipo de Cédula --").Width("100%").ID("actividades")
                                      .DataSource(ViewBag.actividad)
                                    //.DataSource(d => d.Mvc().LoadAction("GetActividades")).DeferRendering(false)
                                    .ElementAttr("class", "form-control").ShowClearButton(true).SearchEnabled(true)
                )*@

                                    </div>
                                </div>
                            </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group">
                                <div class="col-12">
                                    <div id="responsableofp"></div>
                                    @*@(Html.DevExtreme().SelectBoxFor(o => o.Ofp).DisplayExpr("Resultado").ValueExpr("Resultado")
                                                          //.DataSource(d => d.Mvc().LoadAction("GetResponsablesOFP"))
                                                          .Width("100%").DeferRendering(false).ID("responsableofp")
                                                          .DataSource(ViewBag.ofp)
                                                        .Placeholder("-- Seleccione un Responsable de OFP--").ElementAttr("class", "form-control").ShowClearButton(true)
                                    )*@

                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-12">
                                    <div id="embarcacion"></div>
                                    @*@(Html.DevExtreme().AutocompleteFor(o => o.Embarcacion).Width("100%").MinSearchLength(1).ID("embarcacion")
                                                        .DataSource(d => d.Mvc().LoadAction("SearchResultadoGenerico_nombrebarco"))
                                                        //.DataSource(ViewBag.filtro)
                                                        .Placeholder("Nombre del Barco").ElementAttr("class", "form-control").ShowClearButton(true)
                                    )*@

                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-12">
                                    <div id="filtro"></div>
                                    @*@(Html.DevExtreme().SelectBoxFor(o => o.Filtro).DisplayExpr("Resultado").ValueExpr("Resultado")
                                                        //.Value("CEDULAS")
                                                        .Placeholder("-- Seleccione un Filtro --")
                                                        .Width("100%").ID("filtro")
                                                        .DataSource(ViewBag.filtro)
                                                        //.DataSource(d => d.Mvc().LoadAction("GetFiltros")).DeferRendering(false)
                                                        .ElementAttr("class", "form-control").ShowClearButton(true).SearchEnabled(true)
                                    )*@

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div style="text-align: right">
        <div id="btnBuscaLlamada"></div>
        <div id="ToolTip3">Consultar Llamadas</div>
        @*@(Html.DevExtreme().Button().Text("").ID("btnBuscaLlamada").Icon("fas fa-search").Type(ButtonType.Default).StylingMode(ButtonStylingMode.Contained).UseSubmitBehavior(true))
        @(Html.DevExtreme().Tooltip().Target("#btnBuscaLlamada").ShowEvent("mouseenter").HideEvent("mouseleave").ContentTemplate("Consultar Llamadas"))*@
    </div>

   <section>
     
        <script>
                var urlXLS = '@Url.Action("GeneraReporteLlamadasExportarBusqueda", "Llamadas", null, UriHelper.GetDisplayUrl(Context.Request))';
                var urlPDF = '@Url.Action("GeneratePdfLlamadas", "Llamadas", null, UriHelper.GetDisplayUrl(Context.Request))';
        </script>
            <div style="text-align: right; margin-top:5px;margin-bottom:5px;">
                <div class="row">
                    <div class="col-10"></div>
                    <div class="col-1">
                        <div id="exportToExcel"></div>
                        <div id="ToolTip4">Exportar a Excel</div>
                        @*@(Html.DevExtreme().Button().Icon("fa fa-file-excel").ID("exportToExcel").UseSubmitBehavior(false).Type(ButtonType.Success).OnClick(@"function(args){ExportarPDF(urlXLS)}"))
                        @(Html.DevExtreme().Tooltip()
                                            .Target("#exportToExcel")
                                            .ShowEvent("mouseenter")
                                            .HideEvent("mouseleave")
                                            .ContentTemplate("Exportar a Excel")
                        )*@
                    </div>
                    <div class="col-1">
                        <div id="exportToPDF"></div>
                        <div id="ToolTip5">Exportar a PDF</div>
                        @*@(Html.DevExtreme().Button().Icon("fa fa-file-pdf").ID("exportToPDF").UseSubmitBehavior(false).Type(ButtonType.Danger).OnClick(@"function(args){ExportarPDF(urlPDF)}"))
                        @(Html.DevExtreme().Tooltip()
                                            .Target("#exportToPDF")
                                            .ShowEvent("mouseenter")
                                            .HideEvent("mouseleave")
                                            .ContentTemplate("Exportar a PDF")
                        )*@
                    </div>
                </div>
            </div>
            <div id="grid">
                <div id="gridContainer"></div>
                @*@(Html.DevExtreme().DataGrid<MASCore.ModelReference.BuscaLlamadas_Result>()
                            .ID("gridContainer")
                            .DataSource(Model.ResultadoListaLlamadasSP, new string[] { "IdBitaCel" })
                            .ColumnHidingEnabled(true)
                            .ShowColumnLines(true)
                            .ShowRowLines(true)
                            .RowAlternationEnabled(true)
                            .ShowBorders(true)
                            .Pager(p => p
                                .AllowedPageSizes(new int[] { 5, 8, 15, 30 })
                                .ShowInfo(true)
                                .ShowNavigationButtons(true)
                                .ShowPageSizeSelector(true)
                                .Visible(true))
                            .Paging(p => p.PageSize(5))
                            .ShowColumnHeaders(true)
                            .WordWrapEnabled(true)
                            .Columns(columns =>
                            {
                                columns.AddFor(m => m.Fecha).Caption("Fecha").Width(100).Format(Format.ShortDate);
                                columns.AddFor(m => m.Hora).Caption("Hora").Format(Format.ShortTime);
                                columns.AddFor(m => m.Respuesta).Caption("Respuesta");
                                columns.AddFor(m => m.Barco).Caption("Barco");
                                columns.AddFor(m => m.RNP).Caption("RNP");
                                columns.AddFor(m => m.Matricula).Caption("Matrícula");
                                columns.AddFor(m => m.RazonSocial).Caption("Razón Social");
                                columns.AddFor(m => m.OFP).Caption("OFP").Width(200);
                                columns.AddFor(m => m.IdBitaCel).Caption("Acción").CellTemplate(@<text>
                                    <a title="Ver Detalle" id="detalle<%= value %>" href='Details/<%= value %>'>
                                        <i class="dx-icon far fa-folder tamanoIconoEnGrid"></i>
                                    </a>
                                </text>);
                                                    })
                )*@
            </div>
        
    </section>
}

MASCore/MASCore/Views/Llamadas/Delete.cshtml
@model MASCore.ModelReference.TMasBTBitaCel

@{
    ViewBag.Title = "Borrar";
}

<h2>Borrar</h2>

<h3>Esta Seguro de Borar ?</h3>
<fieldset>
    <legend>TMasBTBitaCel</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Actividad)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Actividad)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Barco)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Barco)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RNP)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RNP)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Matricula)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Matricula)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RazonSocial)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RazonSocial)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PuertoBase)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PuertoBase)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Empresa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Empresa)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Atendio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Atendio)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Lugar)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Lugar)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descripcion)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OFP)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OFP)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Borrar" /> |
        @Html.ActionLink("Regresar a Opciones de LLamada", "Index")
    </p>
}

MASCore/MASCore/Views/Llamadas/Index.cshtml
@{
    ViewBag.Title = "Opciones Llamadas";
}
<style>
    .panel {
        margin-bottom: 20px;
        background-color: #2A3F54;
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
        color: white;
    }

    a, a:hover {
        color: #CDA434;
    }
</style>
<div class="index">
    <article>
        <h1>Módulo Llamadas</h1>
    </article>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h4>Panel de Opciones</h4>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="panel">
                                <div class="panel-heading" style="min-height: 75px; max-height: 75px;">
                                    <div class="row">
                                        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                            <i class="fas fa-search fa-1x"></i>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 text-center">
                                            <div><h6>Buscar Llamada(s) </h6></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body" style="background-color:#f5f5f5;color:black">
                                    <p>Ingresando al módulo podrá ver los detalles, editar,imprimir y/o exportar la llamada encontrada.</p>
                                    <br />
                                    <p>También podrá crear una nueva.</p>
                                </div>
                                <a href='@Url.Action("BuscaLlamada", "Llamadas")'>
                                    <div class="panel-footer" style="min-height: 40px; max-height: 40px;">
                                        <div class="text-right">
                                            <i id="ir2" class="fa fa-arrow-circle-right tamanoIconoEnGrid"></i>
                                            
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="panel">
                                <div class="panel-heading" style="min-height: 75px; max-height: 75px;">
                                    <div class="row">
                                        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                            <i class="fas fa-file-alt fa-1x"></i>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 text-center">
                                            <div><h6>Crear Nueva Llamada </h6></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body" style="background-color:#f5f5f5;color:black">
                                    <p>Opción para crear una nueva llamada.</p>
                                </div>
                                <a href='@Url.Action("Create", "Llamadas")'>
                                    <div class="panel-footer" style="min-height: 40px; max-height: 40px;">
                                        <div class="text-right">
                                            <i id="ir1" class="fa fa-arrow-circle-right tamanoIconoEnGrid"></i>
                                            
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
</div>