MASCore/MASCore/Controllers/SolicitantesController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using MASCore.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using MASCore.DataModel;
using Microsoft.AspNetCore.Http;


namespace MASCore.Controllers
{

  
    public class SolicitantesController : Controller
    {
        //private BDMasContextEnt db = new BDMasContextEnt();
        FuncionesProcedimientos FunProc = new FuncionesProcedimientos();

      

        #region "ATRIBUTOS"
        private Byte[] _salt;
        #endregion 
        
        // GET: /Solicitantes/
        public ActionResult Index()
        {
            //return View(db.TMasSolicitantes.ToList()); // codigo Original

            TMasSolInfoCedulas TMSol = new TMasSolInfoCedulas();

            return View(TMSol);
        }

        public ActionResult BuscaSolicitantes()
        {
            SolicitantesModel ModeloTmp = new SolicitantesModel();
            //ModeloTmp.ResultadoListaSolicitantes = db.TMasSolicitantes.ToList();
            return View(ModeloTmp);
        }

        [HttpPost]
        public ActionResult BuscaSolicitantes(SolicitantesModel ModeloTmp)
        {
            List<TMasSolicitantes> ListaSolicitantes = new List<TMasSolicitantes>();
            TMasSolicitantes tmassolicitantes = new TMasSolicitantes();
            if (ModeloTmp.solicitante != null)
                //tmassolicitantes = db.TMasSolicitantes.Single(t => t.Nombre == ModeloTmp.solicitante);

            if (tmassolicitantes.Nombre != null)
                ListaSolicitantes.Add(tmassolicitantes);

            ModeloTmp.ResultadoListaSolicitantes = ListaSolicitantes;

            return View(ModeloTmp);
        }

        // GET: /Solicitantes/Details/5
        public ActionResult Details(int id = 0)
        {
            string UserName = "";
            if (HttpContext.Request.Cookies["userName"] != null)
                UserName = HttpContext.Request.Cookies["userName"];
            ViewBag.Valida7X24 = FunProc.ValidaPermisoUsuario7X24(UserName);
            TMasSolicitantes tmassolicitantes=null;// = db.TMasSolicitantes.Single(t => t.Id_Reg == id);
            if (tmassolicitantes == null)
            {
                return StatusCode(404); 
            }

            return View(tmassolicitantes); 
        }
        
        // GET: /Solicitantes/Create
        public ActionResult Create()
        {
            string UserName = "";
            if (HttpContext.Request.Cookies["userName"] != null)
            UserName = HttpContext.Request.Cookies["userName"];
            ViewBag.Valida7X24 = FunProc.ValidaPermisoUsuario7X24(UserName);
            //ViewBag.estado = FunProc.LlenarResultadoGenerico("estadosolinfo");
            //ViewBag.ciudad = FunProc.BuscaResultadoGenericoConParametrosLista("CIUDADsolinfo", "", "");
            //ViewBag.Litoral = FunProc.LlenarResultadoGenerico("litorales");

            List<TMasSolicitantes> ListaSolicitantes = new List<TMasSolicitantes>();
            TMasSolicitantes Solicitantes = new TMasSolicitantes();
            SolicitantesModel ModeloTmp = new SolicitantesModel();
            ModeloTmp.ResultadoListaSolicitantes = ListaSolicitantes;
            ModeloTmp.Solicitantes = Solicitantes;
            return View(ModeloTmp);
        }
        
        // POST: /Solicitantes/Create
        [HttpPost]
        public ActionResult Create(SolicitantesModel ModeloTmp, string Clave, string Estado, string Ciudad, string estatussolicitante, string estatusweb, string Litoral)
        {
            string UserName = "";
            ViewBag.NoValidoPor = string.Empty;
            if (HttpContext.Request.Cookies["userName"] != null)
                UserName = HttpContext.Request.Cookies["userName"];
            string permiso7x24 = FunProc.ValidaPermisoUsuario7X24(UserName);
            ViewBag.Valida7X24 = permiso7x24;
            //ViewBag.estado = FunProc.LlenarResultadoGenerico("estadosolinfo");
            //ViewBag.ciudad = FunProc.BuscaResultadoGenericoConParametrosLista("CIUDADsolinfo", "", "");
            //ViewBag.Litoral = FunProc.LlenarResultadoGenerico("litorales");

            #region "VALIDACIONES"
            Boolean Valido = true;
            //Agregado por SZ el 08/03/2017
            if (ModeloTmp.Solicitantes.Nombre == null || ModeloTmp.Solicitantes.Nombre.Length == 0)
            {
                ViewBag.NoValidoPor = "El Nombre es Requerido.";
                Valido = false;
            }
            else
            {
                //Agregado por SZ el 17/03/2017
                string nombre = ModeloTmp.Solicitantes.Nombre.ToUpper().Trim();
                //var listNombres = FunProc.LlenarResultadoGenerico("nombres").Where(b=> b.Resultado.Trim() == nombre).ToList();
                //if (listNombres.Count > 0) {
                //    ViewBag.NoValidoPor = "Ese Nombre ya existe, ingrese otro porfavor.";
                //    Valido = false;
                //} 
            }
            //Agregado por SZ el 08/03/2017
            if ((ModeloTmp.Solicitantes.UserName == null || ModeloTmp.Solicitantes.UserName.Length == 0))
            {
                if ((ViewBag.Valida7X24 == "1"))
                {
                    ViewBag.NoValidoPor = "El User Name es Requerido.";
                    Valido = false;
                }
            }
            else
            {
                //Agregado por SZ el 17/03/2017
                string usuario = ModeloTmp.Solicitantes.UserName.ToUpper().Trim();
                //var listUsers = FunProc.LlenarResultadoGenerico("usuarios").Where(b => b.Resultado.Trim() == usuario).ToList();
                //if (listUsers.Count > 0)
                //{
                //    ViewBag.NoValidoPor += "Ese User Name ya existe, ingrese otro porfavor.#-#";
                //    Valido = false;
                //}
            }
            //Agregado por SZ el 08/03/2017
            if ((ModeloTmp.Solicitantes.Password == null || ModeloTmp.Solicitantes.Password.Length == 0)&&(ViewBag.Valida7X24 == "1"))
            {
                ViewBag.NoValidoPor += "El Password es Requerido.#-#";
                Valido = false;
            }
            if (ModeloTmp.Solicitantes.Ciudad == null || ModeloTmp.Solicitantes.Ciudad.Length == 0)
            {
                ViewBag.NoValidoPor += "Seleccione Ciudad.#-#";
                Valido = false;
            }
            //AGREGADO POR SZ EL 26/12/2016
            if (ModeloTmp.Solicitantes.Telefono1 != null)
            {
                Regex Val = new Regex(@"^\d+(\.\d+)?$");
                if (Val.IsMatch(ModeloTmp.Solicitantes.Telefono1))
                {
                    if (ModeloTmp.Solicitantes.Telefono1.Length > 10)
                    {
                        ViewBag.NoValidoPor += "Ingrese solo 10 digitos para Telefono 1.#-#";
                    }
                }
                else
                {
                    ViewBag.NoValidoPor += "El Telefono 1 solo acepta números.#-#";
                    Valido = false;
                }
            }
            if (ModeloTmp.Solicitantes.Telefono2 != null)
            {
                Regex Val = new Regex(@"^\d+(\.\d+)?$");
                if (Val.IsMatch(ModeloTmp.Solicitantes.Telefono2))
                {
                    if (ModeloTmp.Solicitantes.Telefono2.Length > 10)
                    {
                        ViewBag.NoValidoPor += "Ingrese solo 10 digitos para Telefono 2.#-#";
                    }
                }
                else
                {
                    ViewBag.NoValidoPor += "El Telefono 2 solo acepta números.#-#";
                    Valido = false;
                }
            }
            if (ModeloTmp.Solicitantes.Celular != null)
            {
                Regex Val = new Regex(@"^\d+(\.\d+)?$");
                if (Val.IsMatch(ModeloTmp.Solicitantes.Celular))
                {
                    if (ModeloTmp.Solicitantes.Celular.Length > 10)
                    {
                        ViewBag.NoValidoPor += "Ingrese solo 10 digitos para Celular.#-#";
                    }
                }
                else
                {
                    ViewBag.NoValidoPor += "El Celular solo acepta números.#-#";
                    Valido = false;
                }
            }
            if (ModeloTmp.Solicitantes.CorreoInstitucional != null)
            {
                Regex Val = new Regex(@"^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,4})$");
                if (Val.IsMatch(ModeloTmp.Solicitantes.CorreoInstitucional)) { } else {
                    ViewBag.NoValidoPor += "El Correo Institucional no tiene el formato requerido.#-#";
                    Valido = false;
                }
            }
            if (ModeloTmp.Solicitantes.CorreoAlterno != null)
            {
                Regex Val = new Regex(@"^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,4})$");
                if (Val.IsMatch(ModeloTmp.Solicitantes.CorreoAlterno)) { } else {
                    ViewBag.NoValidoPor += "El Correo Alterno no tiene el formato requerido.#-#";
                    Valido = false;
                }
            }
            if (ModeloTmp.Solicitantes.Dependencia == null || ModeloTmp.Solicitantes.Dependencia.Length == 0)
            {
                ViewBag.NoValidoPor += "Ingrese la dependencia.#-#";
                Valido = false;
            }
            #endregion

            if (ModelState.IsValid && Valido)
            {
                if (ModeloTmp.Solicitantes.Dependencia != null || ModeloTmp.Solicitantes.Dependencia.Length > 0)
                {
                    ModeloTmp.Solicitantes.Dependencia = ModeloTmp.Solicitantes.Dependencia.ToUpper();

MASCore/MASCore/Views/Solicitantes/BuscaSolicitantes.cshtml
@model MASCore.Models.SolicitantesModel

@{
    ViewBag.Title = "Busca Solicitantes";
}

<div style="text-align:center; color:Red;font-size:medium">
    @ViewBag.NoValidoPor
</div>

@using (Html.BeginForm("BuscaSolicitantes", "Solicitantes", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h4>Solicitantes</h4>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div id="grid" style="margin-top: 10px;">
                        @(Html.DevExtreme().DataGrid<MASCore.TMasSolicitantes>().DataSource(Model.ResultadoListaSolicitantes)
                            .ColumnHidingEnabled(true).ShowColumnLines(true).ShowRowLines(true).RowAlternationEnabled(true).ShowBorders(true)
                            .Pager(p => p.AllowedPageSizes(new int[] { 5, 8, 15, 30 }).ShowInfo(true).ShowNavigationButtons(true).ShowPageSizeSelector(true).Visible(true))
                            .Paging(p => p.PageSize(5)).ShowColumnHeaders(true).WordWrapEnabled(true)
                            .FilterRow(filterRow => filterRow.Visible(true).ApplyFilter(GridApplyFilterMode.Auto)).Sorting(sorting => sorting.Mode(GridSortingMode.Multiple))
                            .Columns(columns => {
                                columns.AddFor(m => m.Nombre).Caption("Nombre");
                                columns.AddFor(m => m.Cargo).Caption("Cargo");
                                columns.AddFor(m => m.Telefono1).Caption("Teléfono");
                                columns.AddFor(m => m.Celular).Caption("Celular");
                                columns.AddFor(m => m.CorreoInstitucional).Caption("Correo");
                                columns.AddFor(m => m.Dependencia).Caption("Dependencia");
                                columns.AddFor(m => m.Ciudad).Caption("Ciudad");
                                columns.AddFor(m => m.Estado).Caption("Estado");
                                columns.AddFor(m => m.Id_Reg).FilterType(FilterType.Exclude).Caption("Acción").CellTemplate(@<text><a href='Details/<%= value %>'><i class="dx-icon far fa-folder tamanoIconoEnGrid"></i></a></text>);
                            })
                        )
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MASCore/MASCore/Views/Solicitantes/Details.cshtml
@model MASCore.TMasSolicitantes

@{
    ViewBag.Title = "Detalle Solicitante";
}

@using (Html.BeginForm("Details", "Solicitantes", FormMethod.Post, new { @class = "form-horizontal", @id = "miforma" }))
{
    <article>
        <div class="row">
            <div class="col-5">
                <h1>Detalle Solicitante</h1>
            </div>
            <div class="col-7 text-right">
                <script>
                    var idCedula = @Model.Id_Reg;
                    @*var urlComback = '@Url.Action("Index", "Solicitantes", null, Request.Url.Scheme)';
                    var urlEdit = '@Url.Action("Edit", "Solicitantes", null, Request.Url.Scheme)';*@
                </script>
                <div class="row">
                    <div class="col-10"></div>
                    <div class="col-1" style="padding:0">
                        @(Html.DevExtreme().Button().Icon("fas fa-edit").ElementAttr("class", "iconobotonedicion").ID("editarDetalle").UseSubmitBehavior(false).Type(ButtonType.Default).OnClick(@"function(args){edit(urlEdit,'?id='+idCedula)}"))
                        @(Html.DevExtreme().Tooltip().Target("#editarDetalle").ShowEvent("mouseenter").HideEvent("mouseleave").ContentTemplate("Editar"))
                    </div>
                    <div class="col-1" style="padding:0; text-align:center">
                        @(Html.DevExtreme().Button().Icon("fas fa-undo-alt").ID("regresar").UseSubmitBehavior(false).Type(ButtonType.Default).OnClick(@"function(args){comback(urlComback)}"))
                        @(Html.DevExtreme().Tooltip().Target("#regresar").ShowEvent("mouseenter").HideEvent("mouseleave").ContentTemplate("Regresar a la página anterior"))
                    </div>
                </div>
            </div>
        </div>
    </article>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h4>
                    <div class="row">
                        <div class="col-3" style="padding: 8px 0 0 0;margin: 0;text-align: center;">
                            <b>Id Usuario:</b>
                        </div>
                        <div class="col-9" style="padding: 0;margin: 0;">
                            @(Html.DevExtreme().TextBoxFor(model => model.Id_Reg).Disabled(true))
                        </div>
                    </div>
                </h4>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="row col-12">
                    <div class="form" style="width:100%">
                        <div class="dx-fieldset">
                            @if (ViewBag.Valida7X24 == "1")
                            {
                                <div class="dx-field row">
                                    <label class="dx-field-label col-3">Nombre de usuario:</label>
                                    <div class="dx-field-value col-9" style="padding-right: 0;">
                                        @(Html.DevExtreme().TextBoxFor(model => model.UserName).Placeholder("Nombre de usuario").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                    </div>
                                </div>
                            }
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Nombre:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Nombre).Placeholder("Nombre").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Cargo:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Cargo).Placeholder("Cargo").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Estado:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Estado).Placeholder("Estado").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Ciudad:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Ciudad).Placeholder("Ciudad").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Dirección:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Direccion).Placeholder("Dirección").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Dependencia:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Dependencia).Placeholder("Dependencia").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Teléfono 1:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Telefono1).Placeholder("Teléfono 1").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Teléfono 2:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Telefono2).Placeholder("Teléfono 2").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Celular:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Celular).Placeholder("Celular").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Red 1:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Red1).Placeholder("Red 1").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Red 2:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Red2).Placeholder("Red 2").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Correo Institucional:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.CorreoInstitucional).Placeholder("Correo Institucional").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Correo Alterno:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.CorreoAlterno).Placeholder("Correo Alterno").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Litoral:</label>
                                <div class="dx-field-value col-9" style="padding-right: 0;">
                                    @(Html.DevExtreme().TextBoxFor(model => model.Litoral).Placeholder("Litoral").Width("100%").ElementAttr("class", "form-control").ShowClearButton(true).ReadOnly(true))
                                </div>
                            </div>
                            <div class="dx-field row">
                                <label class="dx-field-label col-3">Estatus:</label>
                                <div class="dx-field-label col-9">
                                    @(Html.DevExtreme().SwitchFor(m => m.Activo).Width("30%").SwitchedOffText("ELIMINADO").SwitchedOnText("VIGENTE").ElementAttr("class", "form-control").ReadOnly(true))
                                </div>
                            </div>
                            @if (ViewBag.Valida7X24 == "1")
                            {
                                <div class="dx-field row">
                                    <label class="dx-field-label col-3">Acceso Web:</label>
                                    <div class="dx-field-label col-9">
                                        @(Html.DevExtreme().SwitchFor(m => m.AccesoWeb).Width("30%").SwitchedOffText("ELIMINADO").SwitchedOnText("VIGENTE").ElementAttr("class", "form-control").ReadOnly(true))
                                    </div>
                                </div>
                            }
                            <p>Si el estatus es <b>ELIMINADO</b> el solicitante no aparecerá disponible para crear cedulas de solicitud de información.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MASCore/MASCore/Views/Solicitantes/Index.cshtml
@{
    ViewBag.Title = "Opciones de Solicitantes";
}
<style>
    .panel {
        margin-bottom: 20px;
        background-color: #2A3F54;
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
        color: white;
    }

    a, a:hover {
        color: #CDA434;
    }
</style>
<div class="index">
    <article>
        <h1>Módulo Solicitantes</h1>
    </article>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h4>Panel de Opciones</h4>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="panel">
                                <div class="panel-heading" style="min-height: 75px; max-height: 75px;">
                                    <div class="row">
                                        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                            <i class="fas fa-search fa-1x"></i>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 text-center">
                                            <div><h6>Buscar Solicitantes </h6></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body" style="background-color:#f5f5f5;color:black">
                                    <p>Ingresando al módulo podrá ver los detalles y editar los Solicitantes.</p>
                                </div>
                                <a href='@Url.Action("BuscaSolicitantes", "Solicitantes")'>
                                    <div class="panel-footer" style="min-height: 40px; max-height: 40px;">
                                        <div class="text-right">
                                            <i id="ir2" class="fa fa-arrow-circle-right tamanoIconoEnGrid"></i>
                                            
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="panel">
                                <div class="panel-heading" style="min-height: 75px; max-height: 75px;">
                                    <div class="row">
                                        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                            <i class="fas fa-file-alt fa-1x"></i>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 text-center">
                                            <div><h6>Crear Nuevo Solicitante </h6></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body" style="background-color:#f5f5f5;color:black">
                                    <p>Opción para agregar un nuevo Solicitante.</p>
                                </div>
                                <a href='@Url.Action("Create", "Solicitantes")'>
                                    <div class="panel-footer" style="min-height: 40px; max-height: 40px;">
                                        <div class="text-right">
                                            <i id="ir1" class="fa fa-arrow-circle-right tamanoIconoEnGrid"></i>
                                            
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
</div>